# Generated by Django 4.1.6 on 2023-02-06 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='floors',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='project',
            name='symbol',
            field=models.CharField(max_length=6, unique=True),
        ),
    ]
