# Generated by Django 4.1.6 on 2023-02-06 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings_app', '0002_project_floors_alter_project_symbol'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='type',
            field=models.CharField(choices=[('single family house', 'single family house'), ('workshop', 'workshop'), ('garage', 'garage'), ('semi-detached house', 'semi-detached house'), ('other type', 'other type')], default='other type', max_length=30),
        ),
    ]
