# Generated by Django 4.1.6 on 2023-02-06 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings_app', '0004_project_area_project_date_of_the_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='view',
            field=models.ImageField(blank=True, null=True, upload_to='views'),
        ),
    ]
