# Generated by Django 4.1.6 on 2023-02-22 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings_app', '0006_project_investor_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='type',
            field=models.CharField(choices=[('single family house', 'single family house'), ('semi-detached house', 'semi-detached house'), ('industry', 'industry'), ('redecoration', 'redecoration'), ('other type', 'other type')], default='other type', max_length=30),
        ),
        migrations.CreateModel(
            name='Construction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elevation', models.CharField(choices=[('timber', 'timber'), ('plaster', 'plaster'), ('steel sheet', 'steel sheet'), ('stone', 'stone'), ('other type', 'other type')], default='other type', max_length=30)),
                ('roof', models.CharField(choices=[('flat roof', 'flat roof'), ('open gamble', 'open gamble'), ('hipped roof', 'hipped roof'), ('dormer', 'dormer'), ('other type', 'other type')], default='other type', max_length=30)),
                ('ceiling', models.CharField(choices=[('reinforced concrete', 'reinforced concrete'), ('wood', 'wood'), ('steel beams', 'steel beams'), ('prefabricated', 'prefabricated'), ('other type', 'other type')], default='other type', max_length=30)),
                ('walls', models.CharField(choices=[('reinforced concrete', 'reinforced concrete'), ('wood', 'wood'), ('steel beams', 'steel beams'), ('prefabricated', 'prefabricated'), ('bricks', 'bricks'), ('other type', 'other type')], default='other type', max_length=30)),
                ('materials', models.ManyToManyField(to='buildings_app.project')),
            ],
        ),
    ]
