# Generated by Django 4.1.6 on 2023-02-22 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings_app', '0007_alter_project_type_construction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_first_name', models.CharField(blank=True, max_length=30, null=True)),
                ('author_last_name', models.CharField(blank=True, max_length=30, null=True)),
                ('engineering', models.CharField(choices=[('architecture', 'architecture'), ('construction', 'construction'), ('electricity', 'electricity'), ('sanitary', 'sanitary'), ('other type', 'other type')], default='other type', max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='project',
            name='description',
        ),
        migrations.AddField(
            model_name='project',
            name='ceiling',
            field=models.CharField(choices=[('reinforced concrete', 'reinforced concrete'), ('wood', 'wood'), ('steel beams', 'steel beams'), ('prefabricated', 'prefabricated'), ('other type', 'other type')], default='other type', max_length=30),
        ),
        migrations.AddField(
            model_name='project',
            name='elevation',
            field=models.CharField(choices=[('timber', 'timber'), ('plaster', 'plaster'), ('steel sheet', 'steel sheet'), ('stone', 'stone'), ('other type', 'other type')], default='other type', max_length=30),
        ),
        migrations.AddField(
            model_name='project',
            name='roof',
            field=models.CharField(choices=[('flat roof', 'flat roof'), ('open gamble', 'open gamble'), ('hipped roof', 'hipped roof'), ('dormer', 'dormer'), ('other type', 'other type')], default='other type', max_length=30),
        ),
        migrations.AddField(
            model_name='project',
            name='walls',
            field=models.CharField(choices=[('reinforced concrete', 'reinforced concrete'), ('wood', 'wood'), ('steel beams', 'steel beams'), ('prefabricated', 'prefabricated'), ('bricks', 'bricks'), ('other type', 'other type')], default='other type', max_length=30),
        ),
        migrations.DeleteModel(
            name='Construction',
        ),
        migrations.AddField(
            model_name='author',
            name='buildings',
            field=models.ManyToManyField(to='buildings_app.project'),
        ),
    ]
