# Generated by Django 4.1.6 on 2023-03-01 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buildings_app', '0009_alter_author_buildings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_plot_number', models.TextField(blank=True, max_length=15, null=True)),
                ('place', models.TextField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='building_location',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='buildings_app.location'),
            preserve_default=False,
        ),
    ]
