# Generated by Django 4.1.6 on 2023-03-01 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buildings_app', '0010_location_project_building_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='building_location',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
